### ISSUE TITLE
Improve handling of boolean properties

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/react-onsenui#10]
```
var {icon,, ...others} = this.props;

    if (spin) {
      others['spin'] = true;
    }
```

is not enough, for example if i have `<icon spin />` and an `<icon />`, react does its change algorithm and sees no changes for real, so what we actually have to do is something like that:

```
componentDidUpdate() {
    super.componentDidUpdate();
    var node = ReactDOM.findDOMNode(this);

    if (!this.props.spin && node.hasAttribute('spin')) {
      node.removeAttribute('spin');
    }
  }
```

**Comment by argelius** [comment]
I guess this solved by doing

```
others.spin = spin || null;
```

**Comment by philolo1** [comment]
yeah or using the Util functions, just a reminder that i will need to
refactor.

2016-05-03 13:38 GMT+09:00 Andreas Argelius <notifications@github.com>:
