### ISSUE TITLE
Make Fab and Button submit form

### ISSUE THREAD

**Issue by sntran** [OnsenUI/react-onsenui#105]
Hi,

We have a `Page` with a `List` of `Input` for the user to enter data, and a`Fab` (or `Button` depending on platform) to save. We would like to wrap both the `List` and the `Fab` inside a `<form>` so that we can utilize browser's form validation and bind `onSubmit`. However, since those buttons are not real buttons, they won't submit the form.

I'd rather not bind `onClick` on them to submit the actual `form` node through `refs`. Is there a way to achieve form submission?

**Comment by philolo1** [comment]
Thanks @sntran for your question. We will look into it, but it might be also a good Question to rather look into our community (community.onsen.io)

**Comment by philolo1** [comment]
Mhh, i am not 100% sure, but what is your problem @sntran? The fact that you don't like to use ref? You could use `window.document.form` or `document.getElementById` and set the id of the form if you think this is nicer. I cannot think about something out of my head right now, but please feel free to ask in our community (https://community.onsen.io/).

**Comment by sntran** [comment]
Hi @philolo1 .

I guess my issue is that `<ons-button>`, and by definition, `<Button>` React component, should wrap a HTML `button` element instead of providing custom markup. This way the component is still a valid button, and can act like a button, i.e, submitting the form it is contained in. This is the standard behavior of HTML. And `<Button>` component does not do that.

**Comment by philolo1** [comment]
@sntran we are using Custom Components to enable more functionality for the button. So I guess what you want is that the ons-button works like a normal button for forms. I think this is an enhancment that belongs to rather the core. I think for now you should just use the normal `<button>`, but we might implement something like that in the future.

**Comment by sntran** [comment]
Thank you @philolo1 for opening an issue at OnsenUI/OnsenUI.

**Comment by argelius** [comment]
I will close this since it's an issue in the core.
