### ISSUE TITLE
No unique 'key' prop for children

### ISSUE THREAD

**Issue by emildimitrov** [OnsenUI/react-onsenui#107]
In most of the components unique 'key' prop is not set
You can check the console in http://onsenui.github.io/react-onsenui-kitchensink/demo.html.
Having unique 'key' for each children is critical not only for application performance

**Comment by philolo1** [comment]
@emildimitrov you have to set the keys for now by yourself, take a look at this demo here https://github.com/OnsenUI/react-onsenui/tree/master/demo. We could set automatic keys, but i don't think this is a good idea.

**Comment by emildimitrov** [comment]
Hi :) I tried with the tabbar, but couldn't get how to ensure that every child has key. I'll be happy if could give me direction for example how to ensure this here [https://onsen.io/tutorial/index.html?framework=react&category=Reference&module=tabbar](url)

**Comment by argelius** [comment]
@emildimitrov You can add keys to your pages and tabs like this:

```
  renderTabs: function() {
    return [
      {
        content: <MyTab key='home' title='Home' />,
        tab: <Ons.Tab key='home' label='Home' icon='md-home' />
      },
      {
        content: <MyTab key='settings' title='Settings' />,
        tab: <Ons.Tab key='settings' label='Settings' icon='md-settings' />
      }
    ];
  },
```

This should get rid of the error.

**Comment by NgKhanh** [comment]
@argelius  It shound be on document
