### ISSUE TITLE
JsMutationObserver Error

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui#11]
This is what I get when I do **import Ons from 'react-onsenui';**:

`CustomElements.js:343Uncaught TypeError: Cannot set property 'JsMutationObserver' of undefined`

**Comment by argelius** [comment]
Thanks @mishoboss ! We will take a look at it.

**Comment by mishoboss** [comment]
Hello, using Chrome on desktop for now (development). Updated to latest onsenui and react-onsenui and tested with react-kitchensink - all good now.

**Comment by philolo1** [comment]
Closing it for now, if you have difficulties again, feel free to open the issue or create a new one.
