### ISSUE TITLE
initialIndex in tabbar not displaying correct tab

### ISSUE THREAD

**Issue by hervejegou** [OnsenUI/react-onsenui#110]
I am trying to open a page with tabbar at the second tab instead of the first. I tried to change the initial index from 0 to 1 in the [onsen tutorial] (https://onsen.io/tutorial/index.html?framework=react&category=Reference&module=tabbar) but it does not seem to work:
``
<Ons.Tabbar
        initialIndex={1}
        renderTabs={this.renderTabs}
      />
``

**Comment by philolo1** [comment]
@hervejegou try using normal index we got rid of initialindex i think.

**Comment by philolo1** [comment]
@hervejegou actually the right way to do it is this:
```
<Tabbar
          index={this.state.index}
          onPreChange={(event) =>
            {
              this.setState({index: event.index});
            }
          }
          onPostChange={() => console.log('postChange')}
          onReactive={() => console.log('postChange')}
          position='bottom'
          renderTabs={this.renderTabs}
        />
```

**Comment by hervejegou** [comment]
@philolo1 : Thanks it does make sense now.. Will try it shortly.
