### ISSUE TITLE
Unknown prop `no-status-bar-fill` on <div> tag in ons.tabbar

### ISSUE THREAD

**Issue by hervejegou** [OnsenUI/react-onsenui#114]
ons.tabbar creates a div with prop which raises an unknown props warning in React (not declared??):

![ons tabbbar props warning](https://cloud.githubusercontent.com/assets/771611/17723133/398df6fe-646a-11e6-9ff6-8153c3428c0d.png)

The warning in all its glory:

> 
warning.js:44Warning: Unknown prop `no-status-bar-fill` on ``<div>`` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Tabbar)
    in ons-tabbar (created by Tabbar)
    in Tabbar (created by Community)
    in div (created by Page)
    in ons-page (created by Page)
    in Page (created by Community)
    in ons-splitter-content (created by SplitterContent)
    in SplitterContent (created by Community)
    in ons-splitter (created by Splitter)
    in Splitter (created by Community)
    in div (created by Page)
    in ons-page (created by Page)
   ...

**Comment by philolo1** [comment]
@hervejegou which version are you using? It should be removed in newer version. Please update not only `react-onsenui` but also `onsenui`

**Comment by hervejegou** [comment]
@philolo1 you are correct, I was using:
>
 "onsenui": "^2.0.0-rc.15",
    "react-onsenui": "^0.7.2"

Updated to latest and indeed it is fixed. My mistake. Thanks
