### ISSUE TITLE
SplitterSide collapse prop change doesn't works anymore

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui#127]
SplitterSide collapse prop change doesn't works anymore. If "collapsed" property was set to false, and then set to true, SplitterSide is not collapsed. If initially set to true, it renders collapsed. It worked before as expected.

react-onsenui version: 0.7.7

**Comment by argelius** [comment]
Thanks for reporting @mishoboss !

I have fixed this so it will work in the next version. I will probably release a new version later today.
