### ISSUE TITLE
Add `index` prop to `Carousel` component

### ISSUE THREAD

**Issue by argelius** [OnsenUI/react-onsenui#13]
Right now there is no way to programmatically control the carousel.

I think we should add a prop to do this. I guess `index` is a good name and we can get rid of `initialIndex` since we can just set `initial-index` to current value of `index` when the carousel is mounted.

I made a quick test and it seems to work fine. Haven't pushed anything because I'm not sure what to do with `initialIndex`.

**Comment by philolo1** [comment]
if it works fine, i don't think we need initial index.

**Comment by philolo1** [comment]
@argelius the only problem i see is that then people need to listen to the postChange event and update the index to keep it consistent when the user swipes.

**Comment by philolo1** [comment]
done
