### ISSUE TITLE
Warning: Failed propType: Required prop `renderPage` was not specified in `Navigator`.

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/react-onsenui#14]
The following code yields this error: `Warning: Failed propType: Required prop ``renderPage`` was not specified in Navigator. Check the render method of MainNavigation.` I'm using react-onsenui 0.1.1. I also tried with 0.0.17 and it turns out that there the problem does not occur.

The used code is from the blog example: https://onsen.io/blog/react-onsen-ui-navigator-tabs/

```
class MainNavigation extends React.Component {

  renderScene(route, navigator) {
    // console.log(route, navigator);

    const props = route.props || {};
    props.navigator = navigator;

    return React.createElement(route.component, props);
  }

  render() {
    return (
          <Navigator
              initialRoute={{component: MainPage}}
              renderScene={this.renderScene}
          />
    );
  }
}

ReactDOM.render(<MainNavigation />, document.getElementById('app'));
```

**Comment by corneyl** [comment]
Problem starts at version 0.0.19

**Comment by argelius** [comment]
Thanks @corneyl ! The `renderScene` prop was renamed to `renderPage`.

We will be releasing a website with docs pretty soon. Thanks for trying it out :)

We are very grateful for all reports we get.
