### ISSUE TITLE
Error with Input inside a Toolbar

### ISSUE THREAD

**Issue by SiroDiaz** [OnsenUI/react-onsenui#147]
The aspect of a Input inside a Toolbar is like this
![captura](https://cloud.githubusercontent.com/assets/7469286/18818026/b7f873f2-836e-11e6-99bb-991e2417a671.PNG)
The placeholder is under the text box. Same happens with iOS
Source code:

```
<Toolbar>
    <div className="left">
        {inputSearch}
    </div>
    {title}
    <div className="right">
        <ToolbarButton onClick={this.searchBooks.bind(this)}>
            <Icon icon={iconName} />
        </ToolbarButton>
    </div>
</Toolbar>
```

**Comment by frankdiox** [comment]
Thanks. This was fixed in the core some time ago and will be available from the next release.
