### ISSUE TITLE
Navigator throws warning: Each child in an array or iterator should have a unique "key" prop react@15.3.2

### ISSUE THREAD

**Issue by jasonnathan** [OnsenUI/react-onsenui#155]
When I used the React `<Navigator />` component, following this [tutorial](https://onsen.io/blog/react-onsen-ui-navigator-tabs/#usage), I get this warning in the console:

    Warning: Each child in an array or iterator should have a unique "key" prop. 
    Check the render method of `Navigator`. 
    See https://fb.me/react-warning-keys for more information.
    in _class
    in Navigator (created by _class)
    in _class

Using

    ├─┬ react@15.3.2
    ├── onsenui@2.0.0
    ├── react-onsenui@1.0.0

**Comment by frankdiox** [comment]
@jasonnathan Maybe this is useful: https://github.com/OnsenUI/react-onsenui/issues/107

**Comment by jasonnathan** [comment]
Thanks, perhaps this should be in the docs.
