### ISSUE TITLE
Splitter component does not render when pushing page

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/react-onsenui#16]
I have created this page based upon [this](https://onsen.io/blog/react-onsen-ui-navigator-tabs/) example:
```
class SettingsPage extends React.Component {
  pushPage() {
    this.props.navigator.pushPage({component: SecondPage});
  }

  popPage() {
    this.props.navigator.popPage();
  }

  render() {
    return (
        <Ons.Splitter>
          <Ons.SplitterSide
              side="left"
              width={200}
              isSwipeable={true}
              isCollapsed={true}>
            <Ons.Page>
              Menu
            </Ons.Page>
          </Ons.SplitterSide>
          <Ons.SplitterContent>
            <Ons.Page>
              <Ons.Toolbar>
                <div className="left">
                  <Ons.Button><Ons.Icon icon='md-menu'/></Ons.Button>
                </div>
                <div className="center">Another page</div>
              </Ons.Toolbar>

              <p style={{textAlign: 'center'}}>
                <Ons.Button onClick={this.pushPage.bind(this)}>Push page</Ons.Button>
                <Ons.Button onClick={this.popPage.bind(this)}>Pop page</Ons.Button>
              </p>
            </Ons.Page>
          </Ons.SplitterContent>
        </Ons.Splitter>
    );
  }
}
```
But when pushing this page, the following error occurs:
`Warning: Failed propType: Invalid argument supplied to oneOf, expected an instance of array. Check the render method of SettingsPage.`
When I change the render function to e.g. `return (<Ons.Page>Test</Ons.Page>)`, no error occurs and the page is pushed, so it really seems to be something with the `Splitter` component. When I render the `SettingsPage` component directly, it yields the same error but after rendering and pushing the same page does again not work.

**Comment by argelius** [comment]
Hi!

```
Warning: Failed propType: Invalid argument supplied to oneOf, expected an instance of array. Check the render method of SettingsPage.
```

This error has been fixed. Are you using the latest version?

For pages pushed on top of the `Navigator` they all need to be wrapped in a `Page` component. Try wrapping the `Splitter` component in `Page` and I think it will work.

Thanks for pointing me to the blog post. Some things have changed so I will update it.
