### ISSUE TITLE
Emit error message when pushing non-Page components on top of the Navigator

### ISSUE THREAD

**Issue by argelius** [OnsenUI/react-onsenui#17]
Right now it will fail silently when pushing something that is not a `Page` component on top of the Navigator. Let's add a nice error message since it's a bit confusing.

**Comment by philolo1** [comment]
Should be done in the core, because otherwise we will need to partially
render the component.

**Comment by argelius** [comment]
@philolo1 That's true. Let's add it to the core :)

**Comment by philolo1** [comment]
@argelius did it in the core but also catched some errors in the navigator.
