### ISSUE TITLE
Windows 10 (+Mobile)/UWP Support?

### ISSUE THREAD

**Issue by lamuertepeluda** [OnsenUI/react-onsenui#174]
Hi there,

I'm selecting some React based UI and I'm looking for supporting Android, iOS and Win 10 UWP for a project. This seem really promising but I don't understand if Windows support is planned/possibile.
Any chance react-onsenui could also support Windows 10 UWP (Desktop + Mobile, at least desktop/tablet) in the near future?

For what I got in the documentation, Onsen should also support Windows. Leaving apart the legacy 8.x stuff, is there any chance for Win 10?

Thank you

**Comment by frankdiox** [comment]
@lamuertepeluda I think it should be fine. If you use Visual Studio there is a related [guide here](https://taco.visualstudio.com/en-us/docs/tutorial-onsen/#get-your-app-running-on-windows) for the core library. Windows 10 is listed as supported in the [core library readme](https://github.com/OnsenUI/OnsenUI#browser-support).

**Comment by lamuertepeluda** [comment]
@frankdiox thank you for the pointer. I will give it a try, because from my first tries with the Chrome Developers Tools, which mock up both user agent and screen in [device mode](https://developers.google.com/web/tools/chrome-devtools/device-mode/), React+Onsen seem to only recognize Android and iOS, but I cannot get a windows-styled UI even if I select a "Lumia 950" settings. I only get the iOS or the Android UI.

Style apart, I expect the app to work because I already built UWP apps with different frameworks including React, and they all more or less work fine.

**Comment by frankdiox** [comment]
@lamuertepeluda Oh, we don't provide Windows styles, only Android and iOS. Actually we recently removed Windows from the officially "supported" platform because we don't have resources for testing in Windows right now. It probably works (without Windows styles) but we cannot test.

**Comment by lamuertepeluda** [comment]
@frankdiox I see, thank you for making it clear 😃   
Hope for future reintroduction of the UWP support. In the meanwhile I'll see if the app can work without Windows styles.
