### ISSUE TITLE
tabbar initial index doesnt work with Safari

### ISSUE THREAD

**Issue by JWPapi** [OnsenUI/react-onsenui#179]
Im not using the initialindex prop. Im using the index prop and its working perfect on Firefox and Chrome, but Safari just doesnt take the index prop. So the App is starting with an empty page. Just if I click on one of the tabs a tab appears. And then I can change everything as smooth as expected. But no initial tab.

**Comment by argelius** [comment]
Hi @JWPapi !

The `initialIndex` prop has been removed in favor of the `index` prop. Can you try updating. I tried it in Safari and it is working fine.

**Comment by JWPapi** [comment]
As said im not using the initial index prop. 

https://gist.github.com/JWPapi/12cd5c8ca33f3a8ba83095b3551d8be9

Am I doing anything wrong? I doublechecked everything a 100 times now

**Comment by argelius** [comment]
@JWPapi I'm really sorry. I misread your message. 

Can you give some more information about your platform? I tried the `index` prop on Mobile Safari and it was working fine for me.

**Comment by JWPapi** [comment]
Have you checked my gist?

You could also check https://ffm.nights.cool If I open it in Chrome or Firefox there is a initial tab, but not in Safari. And check my gist above if you havent yet.

I know your Tabbar has a lot of built in props, so you dont have to set a lot on your own to make it work. Even without setting an index and a onPreChange Prop it works on Chrome. Safari doesnt have  React DevTools, so I cant see whats going on :/

**Comment by JWPapi** [comment]
Oh I just checked, on my Mac its working, Its not working on my Windows Safari and not on my test iPhone 5 or 5S (not sure what it is lol). If Im emulating any iPhone its not working there too.

**Comment by JWPapi** [comment]
@argelius is there maybe a workaround, that i tell the tabbar to show the first tab i saw something like setActiveTab in the pure js version

**Comment by JWPapi** [comment]
Actuall it works with your kitchensink demo:

https://onsenui.github.io/react-onsenui-kitchensink/

but not with my code:

https://gist.github.com/JWPapi/2af216e6e1d696e988c07c75900fd7bb

Cant spot any difference

**Comment by JWPapi** [comment]
I think its a problem with:

http://stackoverflow.com/questions/8230380/settimeout-not-working-on-safari-mobile

And it not shown up in your demo app, since you are using babelify and im not. Ill check further on this. Would be awesome if you could check in here, im not that experienced @argelius

**Comment by JWPapi** [comment]
Ok, can stay closed, was totally my fault. I fucked something up in one of my pages, that lead to an error that stopped further  process. Everything is fine. thanks

**Comment by argelius** [comment]
@JWPapi Glad you were able to solve it! :+1:
