### ISSUE TITLE
how to disable default behaviour when clicking BackButton component?

### ISSUE THREAD

**Issue by plrthink** [OnsenUI/react-onsenui#20]
I'm using react-onsenui with redux. One problem that I am currently facing is I need to dispatch some action when pages changing. I am using BackButton component in Toolbar, it seems like the animation is broken if I simply add a onClick props on BackButton component. So is there a way to allow me overwrite the default onClick handler on BackButton component?

**Comment by argelius** [comment]
@pirthink We want to change this as well. Right now it's hard to bind some action to the back button but we want to make it customizable.

This will definitely be added in the next version.

**Comment by argelius** [comment]
@plrthink 

This has been fixed now. Adding an `onClick` prop will override the default behavior.

This example shows how it can be used:
https://github.com/OnsenUI/react-onsenui/blob/master/demo/examples/BackButton.js
