### ISSUE TITLE
When LazyList's length is changed in componentDid/WillMount, LazyList isn't rerendered.

### ISSUE THREAD

**Issue by shota-kobayashi** [OnsenUI/react-onsenui#22]
(I'm not really sure if this is a any issue or my implement is wrong...)
Below code is from kitchensink with a little changes. It shows a blank page although when I click  LazyList area, it'll show lists correctly with 10 items.

```
class InfiniteScroll extends React.Component {
  constructor(props) {
      super(props);
      this.state = { //<--------- added.
          listLength:0
      }
  }

  componentDidMount() { //<--------- added.
    this.setState({listLength:10})
  }

  ....

  render() {
    console.log(this.state.listLength)
    return (
      <Page renderToolbar={this.renderToolbar}>
        <LazyList
          length={this.state.listLength} //<--------- changed. 

  ....
}
```

"onsenui": "2.0.0-rc.4",
"react-onsenui": "0.2.1",
"react": "^15.0.2",
"react-dom": "^15.0.2",

Chrome 50.0.2661.94 (64-bit)

**Comment by shota-kobayashi** [comment]
Sorry, some of my explanation is wrong. The code is ok if I use componentWillMount. When I change the length in componetDidMount or some api's callback, it doesn't work.

**Comment by philolo1** [comment]
Thanks for reporting @shota-kobayashi, i can reproduce, its a bug.

**Comment by philolo1** [comment]
We will release a new version that should fix it.

**Comment by philolo1** [comment]
@shota-kobayashi can you try the newest version whether it works react-onsenui@latest?

**Comment by shota-kobayashi** [comment]
@philolo1 It worked! Thanks!

**Comment by argelius** [comment]
@shota-kobayashi Glad you were able to solve it :)

Closing this now.
