### ISSUE TITLE
Input element 'disabled' prop not working correctly

### ISSUE THREAD

**Issue by jonas-arkulpa** [OnsenUI/react-onsenui#24]
The 'disabled' property of an Input element does not respect the set value.
`<Input type='text' placeholder='Email' float disabled={false} />`
The exact same thing is working with a button.
`<Button ripple disabled={false}>Login</Button>`
This is needed to disable the elements according to states.

**Comment by philolo1** [comment]
@jonas-arkulpa thanks for reporting, I forgot to support this property. Try the newest version of react-onsenui@latest and see whether the issue is gone.

**Comment by jonas-arkulpa** [comment]
@philolo1 thanks for the fast answer and fix.
I apologize I do not have the time to test atm.
Will report back as soon as I work again at this project.

**Comment by jonas-arkulpa** [comment]
@philolo1
The issue is gone. Thanks for the help.

**Comment by philolo1** [comment]
@jonas-arkulpa great I could resolve this quickly!
