### ISSUE TITLE
Grid not working

### ISSUE THREAD

**Issue by jonas-arkulpa** [OnsenUI/react-onsenui#25]
I try to implement Row and Col elements.
First Question: Is there a difference between [Col](https://onsen.io/v2/docs/react/Col.html) and [Column](https://onsen.io/v2/docs/react/Column.html) and which one should I use?

As soon as I insert a Row element I get the following errors:

`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of "XXXPage".`

`Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of "XXXPage".`

`Uncaught Error: fail to get ".page__content" element.`

Do not hesitate to ask for more Information.

**Comment by philolo1** [comment]
Oh its an error, please look at Col and Row. Check out the repo demo folder

**Comment by philolo1** [comment]
@jonas-arkulpa probably you need to put it inside a page. 
<Page>
<Row>
<Col /> 
</Row>
</Page>

Have a look here https://github.com/OnsenUI/react-onsenui/blob/master/demo/examples/RowColumn.js

**Comment by jonas-arkulpa** [comment]
@philolo1 I do it exactly the same as explained in your example link.
It is already in a page element.

**Comment by argelius** [comment]
@jonas-arkulpa I think the website was updated before the actual version was released on npm.

It looks from your error that `Row` or `Col` is undefined so I think the reason is that you are using the previous version.

Try updating to the latest version and it should work. This component was added earlier today ;)

**Comment by argelius** [comment]
I made an example on Codepen and it looks like there is no problem in the latest version:

https://codepen.io/onsen/pen/aNMgVR

**Comment by jonas-arkulpa** [comment]
@argelius I updated from 0.2.5 to 0.2.6 and now it's working correct.
Thanks for your help.

**Comment by argelius** [comment]
@jonas-arkulpa Glad to be able to help! :+1:
