### ISSUE TITLE
Update Input values does not work

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/react-onsenui#26]
If the user sets the value of Input, it does not update.
A possible fix might be
```
componentWillReceiveProps(props) {   const node = ReactDOM.findDOMNode(this);   node.value = props.value;   node.checked = props.checked; }
```

but we need to investigate first.

**Comment by argelius** [comment]
I added some normal `<input>` tags to the example so we can easily checke that `input` and `Input` behave the same.
