### ISSUE TITLE
replacePage in navigator?

### ISSUE THREAD

**Issue by rockneverdies55** [OnsenUI/react-onsenui#29]
Can you guys add `replacePage` hook into the navigator? Underlying onsen navigator has the function available, I don't know why it wasn't put into the react-onsenui component.

**Comment by philolo1** [comment]
Thank you @rockneverdies55 we will look into that, its probably not a big change than can be made quite fast.

**Comment by philolo1** [comment]
@rockneverdies55 I published a new version you can use replacePage how you would pushPage.

**Comment by rockneverdies55** [comment]
:+1: thanks.
