### ISSUE TITLE
Splitter content in split mode overlays the sidebar 

### ISSUE THREAD

**Issue by matoilic** [OnsenUI/react-onsenui#31]
When putting the splitter into "split" mode the style of ons-splitter-content is not updated and missing the `left` style property. Thus, it overlays the sidebar. You can see this behaviour in the tutorial https://onsen.io/tutorial/index.html?framework=react&category=Reference&module=splitter, when you set `isCollapsed` to `false`.

When using the standalone version without React it works properly.

**Comment by argelius** [comment]
Thanks for reporting @matoilic !

We will take a look at this issue.

**Comment by philolo1** [comment]
@matoilic  I looked into your issues and did a pull request to the original OnsenUI repository (https://github.com/OnsenUI/OnsenUI/pull/1442). Ones that is merged, we will inform you. Is this an urgent issue, if so we can search for a workaround for now.

**Comment by argelius** [comment]
@matoilic This has been fixed now and will work in the next version.

**Comment by matoilic** [comment]
Perfect. I'll test it as soon as it's out.

**Comment by argelius** [comment]
@matoilic We just released a new version and this should be fixed now. Please open again if you're still having trouble.
