### ISSUE TITLE
pushPage renders new pages twice.

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/react-onsenui#33]
When I call `navigator.pushPage` it calls `renderPage` twice on the target component. This causes weird transition animations through pages because the component returns to it's initial state before starting the page transition. I suspect that this is also causing flickering on the iPad.

**Comment by philolo1** [comment]
@airamrguez thank you for your work on fixing these issues by yourself. I will look into your code to test whether it works as expected. I am not sure why we did that initially, maybe because we did that on the original navigator in onsenui.
