### ISSUE TITLE
Splitter component does not switch to split mode when in landscape orientation

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/react-onsenui#38]
Using the following code, the `Splitter` component does not switch to split mode when the device (or browser) is in landscape mode, although the attribute `collapse="portrait"` is present.
```
<Ons.Splitter>

    <Ons.SplitterSide
        side="left"
        width="260px"
        collapse="portrait"
        isSwipeable={true}
        isCollapsed={true}>
        <SettingsMenu />
    </Ons.SplitterSide>

    <Ons.SplitterContent>
        <Ons.Page>
            <p>Test</p>
        </Ons.Page>
    </Ons.SplitterContent>

</Ons.Splitter>
```

__Environment__
onsenui@2.0.0-rc.10
react-onsenui@0.4.1
react@15.1.0

**Comment by philolo1** [comment]
@corneyl `isCollapse` is actually setting the property `collapse`, maybe we should change that behaviour. So to make it working, please remove `isCollapse` property:

```
  <Ons.SplitterSide
        side="left"
        width={260}
        collapse="portrait"
        isSwipeable={true}>
        <SettingsMenu />
    </Ons.SplitterSide>

```

**Comment by argelius** [comment]
@corneyl A fix for this has been merged now.

Instead of a boolean `isCollapsed` prop we changed to a `collapse` prop that both supportes boolean values and strings.

**Comment by corneyl** [comment]
Thanks!

@philolo1 I had tried before without `isCollapsed={true}`, but then the menu never collapsed. So possibly the options `isCollapsed` and `collapse` conflicted in some way.

**Comment by philolo1** [comment]
Yes ones we release the new version you just use collapse.
