### ISSUE TITLE
<Dialog /> does not display

### ISSUE THREAD

**Issue by damonmcminn** [OnsenUI/react-onsenui#44]
Using version `0.5.2`:

When `<Dialog />` property `isOpen` set to `true` the dialog does not display. The underlying `<ons-dialog>` element has an inline style of `display: none`. In version `0.4.1` manually removing this caused the dialog to display however in the current version this is no longer the case.

**Comment by mishoboss** [comment]
Experienced the same behaviour

**Comment by philolo1** [comment]
Thank you both, we will look into it today!

**Comment by philolo1** [comment]
@mishoboss @damonmcminn So you start your dialog with isOpen={true}? We have examples where we set it from false to true and that works https://github.com/OnsenUI/react-onsenui/blob/master/demo/examples/Dialog.js, i think the issue/bug is that you set it at the beginning, I will look more deeply.

**Comment by philolo1** [comment]
@mishoboss @damonmcminn i fixed the issue and will do a new release soon, I will tag you ones its released.

**Comment by philolo1** [comment]
@mishoboss @damonmcminn  please try the new version whether it works for you, otherwise feel free to open the issue again.

**Comment by mishoboss** [comment]
It's fixed! Thanks!

**Comment by damonmcminn** [comment]
@philolo1 you were correct that it `isOpen` was set to `true` at initial render.

Thanks!
