### ISSUE TITLE
Error when closing Dialog

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui#45]
`util.js:247 Uncaught SyntaxError: Unexpected token (  
index.js:275(anonymous function) @ index.js:400(anonymous function) @ animator.js:140_dequeueTransition @ animit.js:474done @ animit.js:467(anonymous function) @ animit.js:411_dequeueTransition @ animit.js:474done @ animit.js:467(anonymous function) @ animit.js:529fn @ animit.js:66`

**Comment by philolo1** [comment]
Thanks for reporting! This is actually a bug in chrome due to some naming
issues of the event, but it does not cause any error.

**Comment by philolo1** [comment]
@mishoboss closing this issue since its a chrome bug,

**Comment by philolo1** [comment]
if this causes any real error feel free to open the issue again.

**Comment by mishoboss** [comment]
Seems not causing any real issues, just a nasty console error log.

**Comment by argelius** [comment]
@philolo1 @mishoboss Maybe we should take a look at this again. The error message is very ugly even if it doesn't do anything... :(

**Comment by argelius** [comment]
Apparently it is caused by emitting an event with the name `cancel`. Chrome doesn't like that name :)

**Comment by argelius** [comment]
@mishoboss We have released a new version that fixes this error.
