### ISSUE TITLE
Add `index` prop to Tabbar component

### ISSUE THREAD

**Issue by argelius** [OnsenUI/react-onsenui#46]
Right now the only way to switch tabs programatically is to use the methods. To make the Tabbar component easier to integrate with things like Redux and routing I propose adding an `index` prop and removing the `initialIndex` prop since it will be superfluous.

```jsx
<Tabbar
  index={state.tabIndex}
  ...
/>
```

**Comment by bearcanrun** [comment]
This would be super useful. I've hackily used the methods, but then I get warning: setState(...): Cannot update during an existing state transition — so I'm obviously not integrating them right. 'index' prop would super simplify that though!

**Comment by philolo1** [comment]
@bearcanrun this error occurs most of the time if one forgets that setState is asynchronous. I will look into this index feature.
