### ISSUE TITLE
Any proper way to set dialog width and height?

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui#53]
Any proper way to set dialog width and height?

**Comment by philolo1** [comment]
Right now you cannot set the style, we will try to fix it in `onsenui`, until then, you can set the properties by css classes

```
    ons-dialog, .dialog, .dialog-container {
      width: 300px;
      height: 300px;
    }
```

**Comment by philolo1** [comment]
@mishoboss forgot to tag you here.

**Comment by philolo1** [comment]
I will close it for now, feel free to open it if you are not satisfied and we may try to change it in a more proper way.
