### ISSUE TITLE
BottomToolbar : not setting className

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/react-onsenui#57]
This is due to the core, if the bottom toolbar is already attached at the right position, the class `page-with-bottom-toolbar` is not added to page.

**Comment by philolo1** [comment]
@IliaSky do you know whether this should be fixed now?

**Comment by IliaSky** [comment]
Yes - unless react removes the class for some reason this should already be fixed. Just to be safe though you can still check it before closing the issue :)

**Comment by philolo1** [comment]
Seems to be fixed in the core or at least in the next version it will be :)
