### ISSUE TITLE
Render things outside the page content

### ISSUE THREAD

**Issue by argelius** [OnsenUI/react-onsenui#69]
@philolo1 

I think we need a generic way to render stuff that is outside the page content.

Right now we have some props like `renderToolbar` and `renderBottomToolbar`. I think these are fine but sometimes it's important to also render components like `Fab` and `SpeedDial` outside the page content.

What is a good name for a prop that renders stuff outside the page content? What about `renderFixed` since it would be used to render components that have a fixed position?

**Comment by argelius** [comment]
@philolo1 What do you think about this? Is `renderFixed` a good prop name?

**Comment by philolo1** [comment]
@argelius its fine, but should it take an array?

**Comment by argelius** [comment]
@philolo1 What do you think about it taking either an array or just one element?

Generally you would only put one thing there but I think it's nice to also support an array so they don't need to wrap it in a `<div>`. They could have two fabs, like in Google maps.

**Comment by philolo1** [comment]
@argelius i don't think you can distinguish the return type of a function

**Comment by philolo1** [comment]
so i think it should be a function that returns an array.
