### ISSUE TITLE
Props are not passing down to Pages

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/react-onsenui#71]
__Environment__
Onsen 2 rc 15
React 0.6.2
All

__Encountered problem__
Props are not passing down to Pages through a Navigator component.

__How to reproduce__
https://codepen.io/anon/pen/jAYaOR?editors=0011

**Comment by argelius** [comment]
Thanks for reporting this @airamrguez !

I'm not sure if this is actually a bug. The `initialRoute` is only used for initialization.

Actually we (actually @philolo1) is working on improving the `Navigator` component to make it easier to use with state management libraries like Redux, etc. Basically we are getting rid of the `pushPage` and `popPage`.

**Comment by airamrguez** [comment]
I was not sure about that. I suppose that this will cause to re-render every route in the page stack and will dim performance. I was trying to change the application language but I finally did a resetPageStack that also solves the problem.

Thanks for your feedback!

**Comment by argelius** [comment]
@airamrguez We could limit so only the two top pages on the page stack are rendered. If we do that there would be no performance penalty.
