### ISSUE TITLE
Range Value binding dos not change displayed range

### ISSUE THREAD

**Issue by Mythli** [OnsenUI/react-onsenui#72]
Hey Onsen Team,

The rerender with a different value say from 10 to 50 does not change the displayed range.

`
<Range modifier="material"
                               value={this.state.duration_percentage}
                               onChange={(event) => setTimeout(() => { this.setState({duration_percentage: 10}) }, 200) }
                               style={{ width: '100%' }}
                        />
`

Expected behaviour: Range is displaying 10 percent
Instead: Range displays what was selected.

I also found no hint that it is programmed to hit _onChange in the underlying javascript implementation of the compknent.

**Comment by argelius** [comment]
Thanks for reporting @Mythli !

We will take a look at this. So it is not updating when the state changes? That's definitely a bug so we will look into it. Maybe the `value` prop is not working correctly.
