### ISSUE TITLE
Any way to handle the device back buton in react-onsenui

### ISSUE THREAD

**Issue by geohuz** [OnsenUI/react-onsenui#73]
Seems like there is no way to do this currently right?

**Comment by argelius** [comment]
We don't provide a way to handle this now so you would need to add the `backbutton` event handler manually.

For some of the components it is already supported.The `Navigator` will pop a page when tapping the back button and the dialogs will be hidden if the `isCancelable` prop is set to `true`.

**Comment by geohuz** [comment]
well, I'm trying to disable the android physical back button behaviour, as currently the back button always exist the app and I would like it to act like the "back button" component I added into the page, for example, back to the previous page etc.

**Comment by argelius** [comment]
Did you load `cordova.js` in your app? It's important to use the `backbutton` event.

**Comment by geohuz** [comment]
I tried adding the following code into the main.js:

```
import ons from 'onsenui'
...

ons.ready(function () {
    ons.disableDeviceBackButtonHandler();
    document.addEventListener('backbutton', function () {}, true);
});
```

But it doesn't work, the app just exits after tapping the device back button

**Comment by argelius** [comment]
Can you catch the event by using this?

```
document.addEventListener('backbutton', () => alert('back button pressed!!'));
```

**Comment by geohuz** [comment]
Unfortunately  no alert window popup

**Comment by argelius** [comment]
@geohuz Are you running with Cordova and have `cordova.js` loaded?

**Comment by geohuz** [comment]
No, I just use the onsen-react-ui template and it's scaffoldings, and I'm not sure how to load the cordova.js. But I did merge a cordova folder into onsen project, to try to build the project.

**Comment by argelius** [comment]
@geohuz You can use the [Cordova CLI](https://cordova.apache.org/docs/en/latest/guide/cli/) to create a project.

The back button can not be overriden in normal web apps. You need to use some routing library or the `window.history` functions.

**Comment by argelius** [comment]
@geohuz I will close this issue for now.

Maybe discussions like this are better suited for the [community forum](https://community.onsen.io/).

**Comment by geohuz** [comment]
@argelius , I have a long talk with somebody in the forum, it seems like the device backbutton behaviour is to go back to previous navigation stack, but the problem is on the onsenui-react only. As I'm new to onsenui and only start to use it under onsenui-react, I'm facing the problem of not being able to control the android hardware backbutton behavior. I also ran a example code from official document(react 2.0rc) to verify if it's my problem, but it showed same issue: the backbutton exits the app. Currently I tried to include the cordova.js in my html, and using the code as below:

```
ons.ready(function () {
  ons.disableDeviceBackButtonHandler()
  document.addEventListener('backbutton', function () {alert('Hello')}, false)
})
```

Now the device backbutton works, but I'm facing another problem, how can I code the logic of examining the current active page to either go back to previous page, or if I'm at the homepage, exit app? I saw some code on the Internet and tried, for example, use navigator.getCurrentPage(), and navigator.app.exit(), but In the react version it doesn't have getCurrentPage function. 

Highly appreciated if you can share me some clues.

Thanks

**Comment by argelius** [comment]
Can you describe in detail what you are trying to do with an example?

**Comment by geohuz** [comment]
Ok, here is the code I copied/tested from official document, 

```
import React from 'react';
import ReactDOM from 'react-dom';
import {Page, Tabbar, Tab, Toolbar, Navigator, Button, BackButton} from 'react-onsenui';
import 'onsenui'

var index = 0;

var MyPage = React.createClass({
  renderToolbar: function(route, navigator) {
    const backButton = route.hasBackButton
      ? <BackButton onClick={this.handleClick.bind(this, navigator)}>Back</BackButton>
      : null;

    return (
      <Toolbar>
        <div className='left'>{backButton}</div>
        <div className='center'>{route.title}</div>
      </Toolbar>
    );
  },

  handleClick: function(navigator) {
          navigator.popPage();
  },

  pushPage: function(navigator) {
    navigator.pushPage({
      title: `Another page ${index}`,
      hasBackButton: true
    });

    index++;
  },

  renderPage: function(route, navigator) {
    return (
      <Page key={route.title} renderToolbar={this.renderToolbar.bind(this, route, navigator)}>
        <section style={{margin: '16px', textAlign: 'center'}}>
          <Button onClick={this.pushPage.bind(this, navigator)}>
            Push Page
          </Button>
        </section>
      </Page>
    );
  },

  render: function() {
    return (
      <Navigator
        renderPage={this.renderPage}
        initialRoute={{
          title: 'First page',
          hasBackButton: false
        }}
      />
    );
  }
});


ReactDOM.render(<MyPage />, document.getElementById('app'));
```

the pushpage Button simply give you another page, you can push many pages and use the backbutton on the tabbar to go back. Now run it in the android simulator, tap the device backbutton(not the one we coded on the tabbar), now the app exits regardless of current navigate location. I want the device backbutton acts like the tabbar backbutton, go back to previous page, exit the app only when we are in the homepage.

**Comment by argelius** [comment]
@geohuz This works fine for me in Android. Maybe it's easier if you share the whole project because I'm not really sure why it's not working.

Please share the project and provide the necessary commands to build and deploy to Android.

**Comment by geohuz** [comment]
@argelius , here you go: https://github.com/geohuz/onsenRef

The command I run to deploy:

```
monaca debug
```

then in android I use monaca debugger to run the app

**Comment by geohuz** [comment]
After hours of fighting, I finally get this to work, but I'm still not sure where is the problem. The things I can remember is to upgrade the cordova to the newst 6.2.0 (I was using 4.x) before. Also the monoca react template was upgraded. To make it work I changed the config.xml to the cordova supplied and made a minor change. After all those steps, still include the 

```
<script src="cordova.js"></script>
```
to index.html, and now, remove the custom code in the main.js (no ons.ready), everything works by default!!!

Thanks anyway
