### ISSUE TITLE
'Warning: Unknown prop `no-status-bar-fill` on <div> tag.

### ISSUE THREAD

**Issue by argelius** [OnsenUI/react-onsenui#76]
This warning is shown when running the tests.

**Comment by philolo1** [comment]
@argelius its because OnsenUI is setting 'no-status-bar-fill' without react knowing it. I don't think its a big issue...

**Comment by argelius** [comment]
I agree. Just put it here so we can fix it when we have some time to spare.

**Comment by IliaSky** [comment]
BTW `no-status-bar-fill` should've been removed completely around more than a month ago. 
Right now `ag "no-status-bar-fill"` on `onsenui@master` returns only some code from an older version in `css-components/www/patterns/lib/onsen/js/`, but I guess that shouldn't be used anywhere. Maybe it's used in the tests somehow?

Right now there is a `status-bar-fill` attribute, but it should be added only to our custom tags, not to divs. That being said I guess react should be notified about this attribute too.
