### ISSUE TITLE
Carousel data is not being updated properly when the state changes.

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/react-onsenui#78]
__Environment__
Onsen 2 beta 6
React 0.6.2
iOS 9.2

__Encountered problem__
When the state changes the carousel is not being updated accordingly.

__How to reproduce__

https://codepen.io/anon/pen/zBjjLw?editors=0010

**Comment by argelius** [comment]
Thanks @airamrguez ! We will look into this

**Comment by argelius** [comment]
@airamrguez This has been fixed now. Should work in the next version.
