### ISSUE TITLE
Blank toolbar with Floating Action Button and scroll list

### ISSUE THREAD

**Issue by geohuz** [OnsenUI/react-onsenui#79]
When there is a List with many items, which make the list longer enough for scrolling, adding a floating action button will make the toolbar blank, additionally, the Floating Action Button doesn't stay its position (My case is bottom right).

**Comment by argelius** [comment]
Hi @geohuz 

We recently added a prop called `renderFixed` for the `Page` component. This can be used for things like `Fab` and `SpeedDial` components that should have a fixed position on the page:

Can you try this?

```
<Page renderFixed={() => <Fab position='bottom right'>X</Fab>}>
  ...
</Page>
```

**Comment by geohuz** [comment]
Hi @argelius,  would you pls give me the branch/tag version of the repo so I can pull in? It seems like the current npm version doesn't work. (No Fab displayed)

**Comment by argelius** [comment]
@geohuz Are you using 0.7.1? I just tried it and it's displaying fine. Can you provide a small example that reproduces this issue?

Also, I would like to know what platform and version you are running.

**Comment by geohuz** [comment]
@argelius, my version is 0.6.2, let me upgrade it first

**Comment by argelius** [comment]
@geohuz Thanks! I hope it will work with the new version. This prop was added in `0.7.0`.

**Comment by geohuz** [comment]
@argelius , I'm getting error: 'Uncaught Error: This ons-tab element is must be child of ons-tabbar element.', version is 0.7.1 and platform is android, the render method:

```
      <Page renderFixed={()=> <Fab position='bottom right'>
                                 <Icon icon='md-check' />
                              </Fab>
      }>
        <Toolbar style={{backgroundColor: this.props.bkColor}}>
          <div className='left' style={{flex: 1}}>
            <BackButton></BackButton>
          </div>
          <div className='center' style={{flex: 1, textAlign: 'center'}} >SignIn</div>
          <div className='right' style={{flex: 1}} ></div>
        </Toolbar>
        <div>
          <div id="baiduMap" style={{width: '100%', height: 250}}/>
          <p style={{fontWeight: 'bold'}}>{this.state.locationDesc}</p>
          <List dataSource={this.state.poilist} 
            renderHeader={()=> <ListHeader>附近列表</ListHeader>}
            renderRow={(item)=><ListItem>{item}</ListItem>}
          />
        </div>
      </Page>
```

**Comment by argelius** [comment]
@geohuz I think that error has something to do with the Tabbar component. Can you show the code where you use that as well?

For the `Toolbar` component you should use the `renderToolbar` prop instead of putting it as a child of `Page`:

```
<Page renderToolbar={() => <Toolbar>...</Toolbar>}>
  ...
</Page>
```

**Comment by geohuz** [comment]
@argelius, it seems the upgrade breaking the app, I get the error event without renderFixed.  Basically the app's root component initialize the Naviagator and route, as such:

```
class App extends React.Component {
  renderPage(route, navigator) {
    const props = route.props || {}
    props.navigator = navigator;

    return React.createElement(route.component, props)
  }

  render() {
    return (
      <Navigator 
        initialRoute={{component: MainPage, props: {key: 'main'}}}
        renderPage={this.renderPage}
        animation='slide'
        animationOptions={{duration: '0.2', timing: 'ease-in'}}
      />
    )
  }
}
```

So the MainPage render the tabbar,

```
class MainPage extends React.Component {
  renderTabs() {
    const sections = [
      {page: HomePage, name: 'Home', icon: 'md-home'},
      {page: SettingsPage, name: 'Setting', icon: 'md-settings'}
    ]

    return sections.map((section) => {
      return {
        // Dynamic page rendering
        content: <section.page key={section.name} 
                  title={section.name} navigator={this.props.navigator} 
                 />,
        tab: <Tab style={{backgroundColor: '#000'}} key={section.name} 
          label={section.name} icon={section.icon} />
      }
    })
  }

  render() {
    return (
      <Page>
        <Tabbar
          initialIndex={0}
          renderTabs={this.renderTabs.bind(this)}
        />
      </Page>
    )
  }
}
```

then the HomePage will be linked to other pages via 'pushPage',

```
const HomePage = React.createClass({
  displayLocation (color)  {
    this.props.navigator.pushPage({component: SignIn, props: {bkColor: color}})
  },

 ...
 
  <Col width='50%' style={_.assign({}, homeBlockRight, 
         {backgroundColor: shuffleColors[5]})}
            onClick={()=>this.props.navigator.pushPage({component: BBS, props: {bkColor: shuffleColors[5]}})}
   > 

```

**Comment by argelius** [comment]
@geohuz Can you try again with v0.7.2? Just released it and it fixes an issue with the tabs.

**Comment by geohuz** [comment]
Thanks @argelius , It works perfect now!

**Comment by argelius** [comment]
Great! :tada:
