### ISSUE TITLE
The modal hides when the state is updated.

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/react-onsenui#83]
__Environment__
Onsen 2 rc 15
React 0.7.2
All platforms

__Encountered problem__
The modal hides when the state is updated.

__How to reproduce__
https://codepen.io/anon/pen/XKYgxL

**Comment by philolo1** [comment]
will look into it thanks

**Comment by argelius** [comment]
@airamrguez This should be fixed in the next version.
