### ISSUE TITLE
List's dataSource prop could accept a function.

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/react-onsenui#96]
I think it would be nice if `dataSource` in `List` component could also accept a function that returns an array:

`<List dataSource={this.props.tasks}>`  ===> `<List dataSource={this.filterTasks}>`

**Comment by argelius** [comment]
@frankdiox I think this is a good idea. What do you think @philolo1 ?

**Comment by philolo1** [comment]
@frankdiox if you have a function then you cannot really test equality, so do you want it to be a constant function, meaning if the property changes do we want to re-render the component? What is the benefit in comparison to define a function and assining the property or a state to it?

**Comment by argelius** [comment]
Let's close this for now.
