### ISSUE TITLE
react Tabbar for Android displays above Toolbar when position='top'

### ISSUE THREAD

**Issue by hervejegou** [OnsenUI/react-onsenui#97]
Tabbar should stick below Toolbar in Android Material UI. Right now it cannot be used in top position (which is the default/recommended position for Android Material UI).

![react-tabbar-top](https://cloud.githubusercontent.com/assets/771611/17391983/ead7cf3e-5a4c-11e6-8f52-42de9f789ccb.png)

**Comment by argelius** [comment]
@hervejegou We do support this layout but in that case you need to change the structure of the components. I made an example here that you can take a look at:

https://codepen.io/pen/?&editors=101

Generally the tab hierarchy of iOS and Android apps is quite different so it's not possible to support both with the same component structure. If you want to support both I recommend adding some conditional code that renders different components depending on the platform.

**Comment by hervejegou** [comment]
@argelius Thanks this works well now.. Just one low priority feedback, I do get a warning about props:


> warning.js:44 Warning: Unknown prop `no-status-bar-fill` on `<div>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Tabbar)
    in ons-tabbar (created by Tabbar)
    in Tabbar (created by Community)
    in div (created by Page)
    in ons-page (created by Page)
    in Page (created by Community)
    in ons-splitter-content (created by SplitterContent)
    in SplitterContent (created by Community)
    in ons-splitter (created by Splitter)
    in Splitter (created by Community)
    in div (created by Page)
    in ons-page (created by Page)
    in Page (created by Community)
    in Community (created by MeteorDataContainer)
    in MeteorDataContainer
