### ISSUE TITLE
Transparent toolbar buttons have colored ripple

### ISSUE THREAD

**Issue by hervejegou** [OnsenUI/react-onsenui#98]
modifier='transparent' works well for Toolbar in Android. The toolbar buttons appear in white as per UI guidelines.

However when you click a button in the toolbar, you get an instant square background same color as the normal toolbar. Maybe it should be semi transparent ripple background??

**Comment by argelius** [comment]
Thanks @hervejegou !

We will implement the ripple effect for toolbar buttons in a future version. We have the `Ripple` component but the toolbar button ripple effect is quite different from the normal ripple effect so we will implement it separately.

**Comment by hervejegou** [comment]
OK thanks.. maybe transparent toolbar buttons do not really need ripple??

Right now the problem is that it is not usable:
I use this with a background image as in your example in  [onsen css components patterns](http://components.onsen.io/patterns/)
and when I click the button I have a big green square appearing in button background?? (my toolbar is normally green). See below:

1. transparent toolbar button - normal state:
![transparent toolbar button - normal state](https://cloud.githubusercontent.com/assets/771611/17425266/d8459c14-5afd-11e6-9cfc-042886f5471f.png)

2. transparent toolbar button - clicked state:
![transparent toolbar button - clicked state](https://cloud.githubusercontent.com/assets/771611/17425270/ea2a2e90-5afd-11e6-945c-b4647d7bef3f.png)

**Comment by argelius** [comment]
I will close this for now since this is an issue for the core library
