### ISSUE TITLE
Android popover  with 'isCancelable' does not work once cancelled

### ISSUE THREAD

**Issue by hervejegou** [OnsenUI/react-onsenui#99]
Using the popover [demo](https://onsen.io/tutorial/index.html?framework=react&category=Reference&module=popover) with `` isCancelable={true} ``  :

1. when you cancel with the close button inside the popover, the popover closes properly and it can be used again by clicking on the 'Tap Here' button.
2. if you cancel the popover by clicking outside of the popover, the propover closes properly but it will not work again: clicking on the 'Tap Here'  button will not bring it up again.

![onsenui-react-popover-iscancelable](https://cloud.githubusercontent.com/assets/771611/17392509/76e9b71e-5a50-11e6-994d-b435d8ea9af3.png)

**Comment by argelius** [comment]
@hervejegou Thanks for reporting.

This is actually not a bug. When the popover is cancelled by clicking outside the `onCancel` prop will be executed.

Just add `onChancel={this.hide}` in the demo and it should work fine.

**Comment by hervejegou** [comment]
Thanks it works great now.

**Comment by argelius** [comment]
@hervejegou Glad it helped! :)
